Repository nftchance/charlie, pull requests merged in 2023-04, with the labels that each got.

#23 feat: navbar and footer + wallet connection
  frontend/src/App.tsx
  frontend/src/pages/Account.tsx
  frontend/src/pages/ButtonForm.tsx
  frontend/src/pages/Buttons.tsx
  frontend/src/pages/Hosted.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/pages/Static.tsx
  frontend/src/pages/index.tsx
Labels: enhancement

#25 fix: use connected wallet in button form
  api/button/models.py
  frontend/src/pages/ButtonForm.tsx
  frontend/src/pages/Buttons.tsx
Labels: enhancement

#27 fix: implement ens integration for delegate address (#26)
  api/api/settings.py
  api/api/utils.py
  api/button/models.py
  api/erc20/fixtures/erc20.py
  api/requirements.txt
  frontend/src/pages/ButtonForm.tsx
Labels: enhancement

#28 fix: siwe authentication + better ens
  api/api/admin.py
  api/api/settings.py
  api/api/urls.py
  api/api/views.py
  api/button/migrations/0001_initial.py
  api/button/migrations/0002_alter_button_id.py
  api/button/migrations/0003_rename_hex_color_button_primary_color_button_name_and_more.py
  api/button/migrations/0004_button_description.py
  api/button/migrations/0005_alter_button_description_alter_button_name_and_more.py
  api/button/migrations/0006_alter_button_name_alter_button_primary_color_and_more.py
  api/button/migrations/0007_alter_button_name_alter_button_primary_color_and_more.py
  api/button/models.py
  api/button/serializers.py
  api/button/views.py
  api/erc20/migrations/0001_initial.py
  api/erc20/migrations/0002_alter_erc20_options_alter_erc20_unique_together.py
  frontend/.gitignore
  frontend/example.env
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/ConnectButton.tsx
  frontend/src/components/DisconnectButton.tsx
  frontend/src/components/Navbar/Navbar.tsx
  frontend/src/components/WalletButton.tsx
  frontend/src/components/index.tsx
  frontend/src/contexts/AuthenticationContext.tsx
  frontend/src/contexts/index.tsx
  frontend/src/hooks/index.tsx
  frontend/src/hooks/useAPI.tsx
  frontend/src/hooks/useAuthentication.tsx
  frontend/src/hooks/useAuthenticationSignature.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/Account.tsx
  frontend/src/pages/Button.tsx
  frontend/src/pages/ButtonForm.tsx
  frontend/src/pages/Buttons.tsx
  frontend/src/pages/Static.tsx
  frontend/src/polyfills.ts
  frontend/src/utils/config.tsx
  frontend/src/utils/csrf.tsx
  frontend/src/utils/getBalances.tsx
  frontend/src/utils/getMultiCall.tsx
  frontend/src/utils/index.tsx
  frontend/src/utils/tokens.tsx
Labels: enhancement

#30 feat: architecture improvement
  frontend/src/components/Button/ButtonCard.tsx
  frontend/src/components/Button/ButtonRow.tsx
  frontend/src/components/Button/index.tsx
  frontend/src/components/EasterEgg/EasterEgg.css
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/index.tsx
  frontend/src/index.css
  frontend/src/pages/Account.tsx
  frontend/src/pages/Button.tsx
  frontend/src/pages/ButtonEmbed.css
  frontend/src/pages/ButtonEmbed.tsx
  frontend/src/pages/ButtonForm.tsx
  frontend/src/pages/Buttons.tsx
  frontend/src/pages/Hosted.tsx
  frontend/src/pages/index.tsx
Labels: good first issue

#31 feat: arcify the brand
  frontend/src/components/Button/ButtonCard.tsx
  frontend/src/components/Buttons/ConnectButton.tsx
  frontend/src/components/Buttons/DisconnectButton.tsx
  frontend/src/components/Buttons/WalletButton.tsx
  frontend/src/components/Buttons/index.tsx
  frontend/src/components/ConnectButton.tsx
  frontend/src/components/EasterEgg/EasterEgg.css
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Form/MultiSelect.tsx
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.tsx
  frontend/src/components/index.tsx
  frontend/src/contexts/AuthenticationContext.tsx
  frontend/src/index.css
  frontend/src/pages/Button.tsx
  frontend/src/pages/ButtonForm.tsx
  frontend/src/pages/Buttons.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Static.tsx
Labels: enhancement

#35 feat: fetch client
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/hooks/useAPI.tsx
  frontend/src/pages/Button.tsx
  frontend/src/pages/ButtonEmbed.tsx
  frontend/src/pages/ButtonForm.tsx
  frontend/src/pages/Buttons.tsx
  frontend/src/utils/client.tsx
  frontend/src/utils/index.tsx
Labels: enhancement

#39 feat: design implementation
  frontend/src/components/Button/ButtonEmbed.css
  frontend/src/components/Button/ButtonEmbed.tsx
  frontend/src/components/Button/ButtonPreview.css
  frontend/src/components/Button/ButtonPreview.tsx
  frontend/src/components/Button/index.tsx
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Form/ColorInput.tsx
  frontend/src/components/Form/Input.css
  frontend/src/components/Form/Input.tsx
  frontend/src/components/Form/index.tsx
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.tsx
  frontend/src/components/index.tsx
  frontend/src/contexts/AuthenticationContext.tsx
  frontend/src/contexts/NavbarContext.tsx
  frontend/src/contexts/index.tsx
  frontend/src/hooks/index.tsx
  frontend/src/hooks/useAPI.tsx
  frontend/src/hooks/useClient.tsx
  frontend/src/hooks/useColor.tsx
  frontend/src/hooks/useNavbar.tsx
  frontend/src/index.css
  frontend/src/pages/Account.tsx
  frontend/src/pages/Button.tsx
  frontend/src/pages/ButtonForm.css
  frontend/src/pages/ButtonForm.tsx
  frontend/src/pages/Buttons.tsx
  frontend/src/pages/Hosted.tsx
  frontend/src/pages/Static.tsx
  frontend/src/pages/index.tsx
  frontend/src/utils/client.tsx
  frontend/src/utils/format.tsx
  frontend/src/utils/index.tsx
Labels: enhancement

#42 feat: preparation for production api
  .github/workflows/fly.yml
  api/.dockerignore
  api/Dockerfile
  api/api/settings.py
  api/api/utils.py
  api/example.env
  api/fly.toml
  api/requirements.txt
Labels: good first issue

#45 feat: images
  frontend/package-lock.json
  frontend/package.json
  frontend/public/logos/arbitrum.png
  frontend/public/logos/avalanche.png
  frontend/public/logos/ethereum.png
  frontend/public/logos/optimism.png
  frontend/public/logos/polygon.png
  frontend/src/components/Button/ButtonCard.css
  frontend/src/components/Button/ButtonCard.tsx
  frontend/src/components/Button/ButtonEmbed.css
  frontend/src/components/Button/ButtonEmbed.tsx
  frontend/src/components/Form/Checkbox.css
  frontend/src/components/Form/Checkbox.tsx
  frontend/src/components/Images/BlockchainImages.css
  frontend/src/components/Images/BlockchainImages.tsx
  frontend/src/components/Modal/TokenImage.tsx
  frontend/src/components/Modal/TokenRow.css
  frontend/src/components/Modal/TokenRow.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Profile/ProfileCard.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/index.tsx
  frontend/src/hooks/useClient.tsx
  frontend/src/hooks/useColor.tsx
  frontend/src/index.css
  frontend/src/pages/Button.tsx
  frontend/src/pages/ButtonForm.tsx
  frontend/src/pages/Buttons.tsx
  frontend/src/utils/format.tsx
  frontend/src/utils/getBalances.tsx
  frontend/src/utils/getDelegationInfo.tsx
  frontend/src/utils/index.tsx
Labels: enhancement

#44 fix: csrf
  api/api/settings.py
  frontend/package-lock.json
  frontend/package.json
  frontend/public/logos/arbitrum.png
  frontend/public/logos/avalanche.png
  frontend/public/logos/ethereum.png
  frontend/public/logos/optimism.png
  frontend/public/logos/polygon.png
  frontend/src/components/Button/ButtonCard.css
  frontend/src/components/Button/ButtonCard.tsx
  frontend/src/components/Button/ButtonEmbed.css
  frontend/src/components/Button/ButtonEmbed.tsx
  frontend/src/components/Form/Checkbox.css
  frontend/src/components/Form/Checkbox.tsx
  frontend/src/components/Images/BlockchainImages.css
  frontend/src/components/Images/BlockchainImages.tsx
  frontend/src/components/Modal/TokenImage.tsx
  frontend/src/components/Modal/TokenRow.css
  frontend/src/components/Modal/TokenRow.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Profile/ProfileCard.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/index.tsx
  frontend/src/hooks/useClient.tsx
  frontend/src/hooks/useColor.tsx
  frontend/src/index.css
  frontend/src/pages/Button.tsx
  frontend/src/pages/ButtonForm.tsx
  frontend/src/pages/Buttons.tsx
  frontend/src/utils/format.tsx
  frontend/src/utils/getBalances.tsx
  frontend/src/utils/getDelegationInfo.tsx
  frontend/src/utils/index.tsx
Labels: good first issue

#55 Fix checkboxes
  frontend/src/components/Button/ButtonEmbed.tsx
  frontend/src/components/Form/Checkbox.css
  frontend/src/components/Form/Checkbox.tsx
  frontend/src/components/Modal/TokenRow.css
  frontend/src/components/Modal/TokenRow.tsx
  frontend/src/components/Wallet/ENSNameAvatar.tsx
Labels: bug

#56 feat: analytics and kpi framework
  analytics/arbitrum/delegations_over_time.sql
  analytics/avalanche/delegations_over_time.sql
  analytics/ethereum/delegations_over_time.sql
  analytics/ethereum/total_holders.sql
  analytics/evm/circulating_supply.sql
  analytics/evm/counts_aggregate.sql
  analytics/evm/counts_blockchain.sql
  analytics/evm/delegates.sql
  analytics/evm/delegations_over_time_aggregate.sql
  analytics/evm/delegations_over_time_blockchain.sql
  analytics/evm/delegators.sql
  analytics/evm/heat_pattern.sql
  analytics/evm/market_cap.sql
  analytics/optimism/delegations_over_time.sql
  analytics/polygon/delegations_over_time.sql
  api/erc20/fixtures/erc20.sql
Labels: documentation
